print('Hello, world! Bienvenue à tous les collaborateurs !')
print('Bienvenue dans notre application collaborative !')
print('Fonctionnalité de tableau de bord ajoutée par Etudiant B.')
print("Bienvenue dans notre application collaborative !")
print('Fonctionnalité de login ajoutée par Etudiant A.')
